name: al_makkah
description: A new Flutter project.



version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  flutter_bloc: ^8.1.1
  injectable: ^2.1.0
  build_runner: ^2.3.3
  logger: ^1.1.0
  auto_route_generator: ^5.0.3
  injectable_generator: ^2.1.3
  firebase_core: ^2.4.0
  cloud_firestore: ^4.3.0
  freezed: ^2.3.2
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


