// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1zeA9T8EEXNU0iDHEvvf0hgdB-p6nBc8',
    appId: '1:749734272753:web:64cf19d33e1b1aea58d350',
    messagingSenderId: '749734272753',
    projectId: 'al-makkah-faheem',
    authDomain: 'al-makkah-faheem.firebaseapp.com',
    storageBucket: 'al-makkah-faheem.appspot.com',
    measurementId: 'G-P6HC24Z1KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0STj3-DdkDDvUFqAti0a1Ae8QIt8ozY',
    appId: '1:749734272753:android:9c9c3ff6d3d2affd58d350',
    messagingSenderId: '749734272753',
    projectId: 'al-makkah-faheem',
    storageBucket: 'al-makkah-faheem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdu41QZ-8khsmBiBXxkq9XWXQykyLySNA',
    appId: '1:749734272753:ios:c69c150529f4ddb858d350',
    messagingSenderId: '749734272753',
    projectId: 'al-makkah-faheem',
    storageBucket: 'al-makkah-faheem.appspot.com',
    iosClientId: '749734272753-5mqvoc8e6p9ulg9j32sit5lol5uaqs42.apps.googleusercontent.com',
    iosBundleId: 'com.example.alMakkah',
  );
}
